export type TaskState =
  | "DRAFT"
  | "ASSIGNED"
  | "SEEN"
  | "ACCEPTED"
  | "IN_PROGRESS"
  | "WAITING"
  | "BLOCKED"
  | "REVIEW"
  | "COMPLETED"
  | "APPROVED"
  | "REJECTED"
  | "CANCELLED"
  | "OVERDUE"
  | "ON_HOLD"
  | "NEEDS_CLARIFICATION";

const ALLOWED_TRANSITIONS: Record<TaskState, TaskState[]> = {
  DRAFT: ["ASSIGNED", "CANCELLED"],
  ASSIGNED: ["SEEN", "ACCEPTED", "REJECTED", "CANCELLED"],
  SEEN: ["ACCEPTED", "REJECTED", "NEEDS_CLARIFICATION", "CANCELLED"],
  ACCEPTED: ["IN_PROGRESS", "ON_HOLD", "CANCELLED"],
  IN_PROGRESS: ["WAITING", "BLOCKED", "REVIEW", "COMPLETED", "ON_HOLD", "CANCELLED"],
  WAITING: ["IN_PROGRESS", "BLOCKED", "CANCELLED"],
  BLOCKED: ["IN_PROGRESS", "ON_HOLD", "CANCELLED"],
  NEEDS_CLARIFICATION: ["ACCEPTED", "REJECTED", "CANCELLED"],
  ON_HOLD: ["IN_PROGRESS", "CANCELLED"],
  REVIEW: ["APPROVED", "REJECTED", "IN_PROGRESS"],
  REJECTED: ["IN_PROGRESS", "CANCELLED"],
  COMPLETED: ["REVIEW", "APPROVED"],
  APPROVED: [],
  CANCELLED: [],
  OVERDUE: ["IN_PROGRESS", "REVIEW", "CANCELLED"],
};

export function canTransition(current: TaskState, next: TaskState): boolean {
  return ALLOWED_TRANSITIONS[current]?.includes(next) ?? false;
}